storageFile:
  airports: ${} # add your location here in the brackets
  flights: ${} # add your location here in the brackets

spring:
  liquibase:
    enabled: true
    change-log: classpath:db/master.xml
    drop-first: false
  datasource:
    username: ${DB_USER}
    url: ${DB_URL}
    password: ${DB_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
